site_name: pysdbapi
edit_uri: ""
theme:
  features:
    - navigation.tracking
    - navigation.top
  logo: /assets/logo.png
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Off

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: On

nav:
  - Index: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
          link: /en/
        ru:
          name: Russian
          link: /ru/
